rvm:
  - jruby-19mode
  - 1.9.3
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head

before_install:
  - gem update bundler

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx

notifications:
  email:
    on_success: change # only send if status changes
